pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        maven {
            url = 'https://maven.aliyun.com/repository/spring'
            content {
                includeGroupByRegex 'org\\.springframework(\\..*)?'
                includeGroup 'org.springframework.boot'
                includeGroupByRegex 'io\\.spring(\\..*)?'
            }
        }
    }
}

rootProject.name = 'keystone'

include 'keystone-admin'
include 'keystone-common'
include 'keystone-domain'
include 'keystone-framework-admin'
include 'keystone-framework-domain'
include 'keystone-framework-spring-boot-starter'
include 'keystone-infrastructure'
