name: Release and Publish

on:
  push:
    tags:
      - 'v*'  # 仅当 push tag 时触发

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Configure Maven settings
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0">
            <servers>
              <server>
                <id>github</id>
                <username>${{ secrets.GITHUB_USERNAME }}</username>
                <password>${{ secrets.GITHUB_PAT }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Build Project
        run: mvn clean package -DskipTests

      - name: Deploy to GitHub Packages
        run: mvn deploy -DskipTests
        env:
          GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: |
            **/target/*.jar
            !**/target/original-*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
